### PR TITLE
fixed bluegenes navigation issue

### LINKED ISSUE #6: Navigate to query when clicking on a bar
I added a `navigate` function to the tool API, which is [passed as the 6th argument](https://github.com/uosl/bluegenes/blob/feature/improve-tools/docs/tools/tool-api.md#indexjs) to the tool main function, which can be used like this `navigate('query', myQueryObj);`, where you'll want `myQueryObj` to be similar to the object below.

All the Gene ID's will come from the list (I *think* they're returned from the `enrichment` call) and the GO term code will be the one clicked.

```
{
      "model": {
        "name": "genomic"
      },
      "select": [
        "Gene.secondaryIdentifier",
        "Gene.symbol",
        "Gene.primaryIdentifier",
        "Gene.organism.name",
        "Gene.goAnnotation.ontologyTerm.identifier",
        "Gene.goAnnotation.ontologyTerm.name",
        "Gene.goAnnotation.ontologyTerm.parents.identifier",
        "Gene.goAnnotation.ontologyTerm.parents.name"
      ],
      "where": [
        {
          "path": "Gene",
          "op": "IN",
          "code": "A",
          "ids": [
            1007941,
            1009359,
            1010020,
            1069069,
            1085883,
            1092581,
            1103527,
            1117091,
            1126873,
            1128788,
            1141026,
            1172088,
            1177376,
            1194292,
            1234233,
            1243313,
            1245718,
            1259594,
            1264304,
            1284464
          ]
        },
        {
          "path": "Gene.goAnnotation.ontologyTerm.parents.identifier",
          "op": "ONE OF",
          "values": [
            "GO:0001946"
          ]
        }
      ],
      "title": "GO:0001946"
    }
```

### LINKED ISSUE #9: Remove Go Term vs P-value chart
I spoke with Rachel and she said the top chart (*Go Term vs P-value*) wasn't that useful, so we can remove it and only keep the *Go Term vs Gene Count* chart.

### PR DESCRIPTION
**Pull request by akshatbhargava123**
- fixes #6 
- closes #9

### CODE REVIEW

**Comment by heralden** [comment]
Thanks! It works, although I encountered some oddity when doing `npm run build` and using it in bluegenes.

It will throw `type error: t is not a function` when clicking on a bar if `minimize` was set to true in the webpack config. If I change *navigationQuery.js* to export a regular function instead of arrow function, it will work even when `minimize` is set to true.

Seems like webpack isn't optimizing ES6 code correctly. Any ideas how to fix this?

If you don't have time to look at this, I'll just change it to be a regular function and merge this.

**Comment by akshatbhargava123** [comment]
Hey @uosl , I'm not sure why you're facing the issue. I tried the reproducing it by running the build command but it didn't produce any error for me. Any guesses?

If you don't face the issue anymore, please merge the PR, it also removed the GO-Term vs P-value chart.

**Comment by heralden** [comment]
You're right, I did an `npm install` followed by a fresh build and I can't reproduce the problem anymore.

It seems you have removed the *go-term vs* **count** test instead of the *go-term vs* **p-value** test, causing the tests to fail. Could you fix this before I merge?

**Comment by akshatbhargava123** [comment]
Sorry, mistakenly did such a blunt mistake. Fixed it, please check.

**Comment by heralden** [comment]
No worries. Thanks for the quick fix!

**Pull request merged**
